### ISSUE TITLE
Issue with YahooFinance API

### ISSUE THREAD

**Issue by tonynguyen0523** [tonynguyen0523/Stock-App#2]
On startup, this error occurs.

09-15 23:50:54.896 12188-12258/com.udacity.stockhawk E/AndroidRuntime: FATAL EXCEPTION: IntentService[QuoteIntentService]
                                                                       Process: com.udacity.stockhawk, PID: 12188
                                                                       java.lang.StringIndexOutOfBoundsException: length=6; regionStart=0; regionLength=-1
                                                                           at java.lang.String.substring(String.java:1931)
                                                                           at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:126)
                                                                           at yahoofinance.quotes.stock.StockQuotesRequest.parseCSVLine(StockQuotesRequest.java:11)
                                                                           at yahoofinance.quotes.QuotesRequest.getResult(QuotesRequest.java:95)
                                                                           at yahoofinance.YahooFinance.getQuotes(YahooFinance.java:355)
                                                                           at yahoofinance.YahooFinance.get(YahooFinance.java:207)
                                                                           at yahoofinance.YahooFinance.get(YahooFinance.java:186)
                                                                           at com.udacity.stockhawk.sync.QuoteSyncJob.getQuotes(QuoteSyncJob.java:69)
                                                                           at com.udacity.stockhawk.sync.QuoteIntentService.onHandleIntent(QuoteIntentService.java:18)
                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tonynguyen0523** [comment]
Updated yahooFinance API build from 3.5.0 to 3.8.0 in build.gradle(app)
